# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user/user.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fuser/user.proto\x12\x04user\"H\n\x11OAuthLoginRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12%\n\x08provider\x18\x02 \x01(\x0e\x32\x13.user.OAuthProvider\">\n\x12OAuthLoginResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x12\n\ntoken_type\x18\x02 \x01(\t*J\n\rOAuthProvider\x12\x1e\n\x1aOAUTH_PROVIDER_UNSPECIFIED\x10\x00\x12\x19\n\x15OAUTH_PROVIDER_GITHUB\x10\x01\x32H\n\x04User\x12@\n\x0boauth_login\x12\x17.user.OAuthLoginRequest\x1a\x18.user.OAuthLoginResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user.user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OAUTHPROVIDER']._serialized_start=163
  _globals['_OAUTHPROVIDER']._serialized_end=237
  _globals['_OAUTHLOGINREQUEST']._serialized_start=25
  _globals['_OAUTHLOGINREQUEST']._serialized_end=97
  _globals['_OAUTHLOGINRESPONSE']._serialized_start=99
  _globals['_OAUTHLOGINRESPONSE']._serialized_end=161
  _globals['_USER']._serialized_start=239
  _globals['_USER']._serialized_end=311
# @@protoc_insertion_point(module_scope)
