# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import user_pb2 as user_dot_user__pb2


class UserStub(object):
    """User service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.oauth_login = channel.unary_unary(
                '/user.User/oauth_login',
                request_serializer=user_dot_user__pb2.OAuthLoginRequest.SerializeToString,
                response_deserializer=user_dot_user__pb2.OAuthLoginResponse.FromString,
                )


class UserServicer(object):
    """User service
    """

    def oauth_login(self, request, context):
        """
        OAuth login

        args: OAuthLoginRequest
        returns: OAuthLoginResponse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'oauth_login': grpc.unary_unary_rpc_method_handler(
                    servicer.oauth_login,
                    request_deserializer=user_dot_user__pb2.OAuthLoginRequest.FromString,
                    response_serializer=user_dot_user__pb2.OAuthLoginResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user.User', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class User(object):
    """User service
    """

    @staticmethod
    def oauth_login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.User/oauth_login',
            user_dot_user__pb2.OAuthLoginRequest.SerializeToString,
            user_dot_user__pb2.OAuthLoginResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
